language: python
python:
  - "3.6"
  
install:
  - pip install codeclimate-test-reporter
  - pip install coveralls
  
after_success:
  - coveralls
  - codeclimate-test-reporter
  
script:
  coverage run --source=kanjidb setup.py test