language: python
  
install:
  - pip install "coverage>=4.0,<4.4"
  - pip install codeclimate-test-reporter
  - pip install coveralls
  
jobs:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
    after_success:
    - coveralls
    - codeclimate-test-reporter

script:
  coverage run --source=kanjidb setup.py test