version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
	  - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
		    python --version
            pip install -q --user --ignore-installed --upgrade virtualenv
            pip install -q tox --user
            pip install -q coverage --user
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
          name: Prepare Env
      - run:
          command: coverage run --source=kanjidb setup.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
