version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            pip install -q coverage --user
            echo $HOME
          name: Prepare Env
      - run:
          command: |
            $HOME/.local/bin/coverage run --source=kanjidb setup.py test
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
          name: Run Tests
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
